package com.hamidjonhamidov.cvforkhamidjon.ui.c_source_code

import com.hamidjonhamidov.cvforkhamidjon.R
import com.hamidjonhamidov.cvforkhamidjon.ui.c_source_code.custom_treeview.PathFile

object StaticData {

    val leafFileList = listOf(
        PathFile(listOf("res", "color", "nav_title_color"), R.raw.nav_title_color),
        PathFile(listOf("res", "color", "project_color"), R.raw.project_color),
        PathFile(listOf("res", "color", "nav_icon_color"), R.raw.nav_icon_color),
        PathFile(listOf("res", "color", "link_color"), R.raw.link_color),
        PathFile(listOf("res", "menu", "only_refresh_menu"), R.raw.only_refresh_menu),
        PathFile(listOf("res", "menu", "source_code_menu"), R.raw.source_code_menu),
        PathFile(listOf("res", "menu", "drawer_menu"), R.raw.drawer_menu),
        PathFile(listOf("res", "menu", "home_menu"), R.raw.home_menu),
        PathFile(listOf("res", "menu", "contact_menu"), R.raw.contact_menu),
        PathFile(listOf("res", "menu", "bottom_nav_menu"), R.raw.bottom_nav_menu),
        PathFile(listOf("res", "values", "strings"), R.raw.strings),
        PathFile(listOf("res", "values", "colors"), R.raw.colors),
        PathFile(listOf("res", "values", "dimens"), R.raw.dimens),
        PathFile(listOf("res", "values", "styles"), R.raw.styles),
        PathFile(listOf("res", "navigation", "contact_nav_graph"), R.raw.contact_nav_graph),
        PathFile(listOf("res", "navigation", "algorithms_nav_graph"), R.raw.algorithms_nav_graph),
        PathFile(listOf("res", "navigation", "others_nav_graph"), R.raw.others_nav_graph),
        PathFile(listOf("res", "navigation", "android_nav_graph"), R.raw.android_nav_graph),
        PathFile(listOf("res", "navigation", "main_nav_graph"), R.raw.main_nav_graph),
        PathFile(listOf("res", "drawable", "send_btn"), R.raw.send_btn),
        PathFile(listOf("res", "drawable", "android_bottom"), R.raw.android_bottom),
        PathFile(listOf("res", "drawable", "ic_reduce_all"), R.raw.ic_reduce_all),
        PathFile(listOf("res", "drawable", "ic_launcher_background"), R.raw.ic_launcher_background),
        PathFile(listOf("res", "drawable", "card_selector"), R.raw.card_selector),
        PathFile(listOf("res", "drawable", "file_type_blue_folder"), R.raw.file_type_blue_folder),
        PathFile(listOf("res", "drawable", "message_contact"), R.raw.message_contact),
        PathFile(listOf("res", "drawable", "selected_state"), R.raw.selected_state),
        PathFile(listOf("res", "drawable", "ic_3d_rotation_black_24dp"), R.raw.ic_3d_rotation_black_24dp),
        PathFile(listOf("res", "drawable", "expand_default"), R.raw.expand_default),
        PathFile(listOf("res", "drawable", "custom_rotate_pressed"), R.raw.custom_rotate_pressed),
        PathFile(listOf("res", "drawable", "custom_send_et"), R.raw.custom_send_et),
        PathFile(listOf("res", "drawable", "phone_contact"), R.raw.phone_contact),
        PathFile(listOf("res", "drawable", "backgr_change"), R.raw.backgr_change),
        PathFile(listOf("res", "drawable", "download"), R.raw.download),
        PathFile(listOf("res", "drawable", "unread_img"), R.raw.unread_img),
        PathFile(listOf("res", "drawable", "read_img"), R.raw.read_img),
        PathFile(listOf("res", "drawable", "back_arrow"), R.raw.back_arrow),
        PathFile(listOf("res", "drawable", "custom_rotate_default"), R.raw.custom_rotate_default),
        PathFile(listOf("res", "drawable", "more_bottom_nav"), R.raw.more_bottom_nav),
        PathFile(listOf("res", "drawable", "color_cursor_et"), R.raw.color_cursor_et),
        PathFile(listOf("res", "drawable", "algorithms_bottom_nav"), R.raw.algorithms_bottom_nav),
        PathFile(listOf("res", "drawable", "background_gradient"), R.raw.background_gradient),
        PathFile(listOf("res", "drawable", "ic_expand_all"), R.raw.ic_expand_all),
        PathFile(listOf("res", "drawable", "custom_rotate_btn"), R.raw.custom_rotate_btn),
        PathFile(listOf("res", "drawable", "exit"), R.raw.exit),
        PathFile(listOf("res", "animator", "back_animator"), R.raw.back_animator),
        PathFile(listOf("res", "animator", "front_animator"), R.raw.front_animator),
        PathFile(listOf("res", "anim", "fade_in"), R.raw.fade_in),
        PathFile(listOf("res", "anim", "slide_out_right"), R.raw.slide_out_right),
        PathFile(listOf("res", "anim", "slide_up_anim"), R.raw.slide_up_anim),
        PathFile(listOf("res", "anim", "slide_out_left"), R.raw.slide_out_left),
        PathFile(listOf("res", "anim", "slide_in_left"), R.raw.slide_in_left),
        PathFile(listOf("res", "anim", "slide_down_anim"), R.raw.slide_down_anim),
        PathFile(listOf("res", "anim", "fade_out"), R.raw.fade_out),
        PathFile(listOf("res", "anim", "slide_in_right"), R.raw.slide_in_right),
        PathFile(listOf("res", "layout", "activity_main"), R.raw.activity_main),
        PathFile(listOf("res", "layout", "fragment_about_app"), R.raw.fragment_about_app),
        PathFile(listOf("res", "layout", "fragment_home"), R.raw.fragment_home),
        PathFile(listOf("res", "layout", "fragment_android_fragment"), R.raw.fragment_android_fragment),
        PathFile(listOf("res", "layout", "project_list_item"), R.raw.project_list_item),
        PathFile(listOf("res", "layout", "skill_item_layout"), R.raw.skill_item_layout),
        PathFile(listOf("res", "layout", "fragment_details"), R.raw.fragment_details),
        PathFile(listOf("res", "layout", "fragment_algorithms"), R.raw.fragment_algorithms),
        PathFile(listOf("res", "layout", "fragment_my_skills"), R.raw.fragment_my_skills),
        PathFile(listOf("res", "layout", "single_message_him"), R.raw.single_message_him),
        PathFile(listOf("res", "layout", "single_message_me"), R.raw.single_message_me),
        PathFile(listOf("res", "layout", "activity_achievments"), R.raw.activity_achievments),
        PathFile(listOf("res", "layout", "nav_header_main"), R.raw.nav_header_main),
        PathFile(listOf("res", "layout", "fragment_contact_me"), R.raw.fragment_contact_me),
        PathFile(listOf("res", "layout", "fragment_posts"), R.raw.fragment_posts),
        PathFile(listOf("res", "layout", "post_item"), R.raw.post_item),
        PathFile(listOf("res", "layout", "fragment_projects"), R.raw.fragment_projects),
        PathFile(listOf("res", "layout", "fragment_others"), R.raw.fragment_others),
        PathFile(listOf("res", "layout", "fragment_about_me"), R.raw.fragment_about_me),
        PathFile(listOf("res", "layout", "activity_code_view"), R.raw.activity_code_view),
        PathFile(listOf("res", "layout", "info_dialog"), R.raw.info_dialog),
        PathFile(listOf("res", "layout", "activity_source_code"), R.raw.activity_source_code),
        PathFile(listOf("res", "layout", "activity_contact"), R.raw.activity_contact),
        PathFile(listOf("res", "layout", "notification_layout"), R.raw.notification_layout),
        PathFile(listOf("res", "layout", "achievement_item"), R.raw.achievement_item),
        PathFile(listOf("cvforkhamidjon", "repository", "achievments", "AchievementsRepositoryImpl"), R.raw.achievementsrepositoryimpl),
        PathFile(listOf("cvforkhamidjon", "repository", "achievments", "AchievementsRepository"), R.raw.achievementsrepository),
        PathFile(listOf("cvforkhamidjon", "repository", "contacs", "ContactsRepositoryImpl"), R.raw.contactsrepositoryimpl),
        PathFile(listOf("cvforkhamidjon", "repository", "contacs", "ContactsRepository"), R.raw.contactsrepository),
        PathFile(listOf("cvforkhamidjon", "repository", "contacs", "MessageResponse"), R.raw.messageresponse),
        PathFile(listOf("cvforkhamidjon", "repository", "NetworkApiCall"), R.raw.networkapicall),
        PathFile(listOf("cvforkhamidjon", "repository", "main", "MainRepositoryImpl"), R.raw.mainrepositoryimpl),
        PathFile(listOf("cvforkhamidjon", "repository", "main", "MainRepository"), R.raw.mainrepository),
        PathFile(listOf("cvforkhamidjon", "viewmodelfactory", "AchievementsViewModelFactory"), R.raw.achievementsviewmodelfactory),
        PathFile(listOf("cvforkhamidjon", "viewmodelfactory", "MainViewModelFactory"), R.raw.mainviewmodelfactory),
        PathFile(listOf("cvforkhamidjon", "viewmodelfactory", "ContactsViewModelFactory"), R.raw.contactsviewmodelfactory),
        PathFile(listOf("cvforkhamidjon", "data_requests", "api", "achievments", "AchievmentsApiService"), R.raw.achievmentsapiservice),
        PathFile(listOf("cvforkhamidjon", "data_requests", "api", "main", "MainApiService"), R.raw.mainapiservice),
        PathFile(listOf("cvforkhamidjon", "data_requests", "api", "contacts", "ContactsApiService"), R.raw.contactsapiservice),
        PathFile(listOf("cvforkhamidjon", "data_requests", "persistence", "achievments", "AchievementsDao"), R.raw.achievementsdao),
        PathFile(listOf("cvforkhamidjon", "data_requests", "persistence", "AppDatabase"), R.raw.appdatabase),
        PathFile(listOf("cvforkhamidjon", "data_requests", "persistence", "main", "AboutMeDao"), R.raw.aboutmedao),
        PathFile(listOf("cvforkhamidjon", "data_requests", "persistence", "main", "PostsDao"), R.raw.postsdao),
        PathFile(listOf("cvforkhamidjon", "data_requests", "persistence", "main", "ProjectsDao"), R.raw.projectsdao),
        PathFile(listOf("cvforkhamidjon", "data_requests", "persistence", "main", "SkillsDao"), R.raw.skillsdao),
        PathFile(listOf("cvforkhamidjon", "data_requests", "persistence", "Converters"), R.raw.converters),
        PathFile(listOf("cvforkhamidjon", "data_requests", "persistence", "contact", "ContactsDao"), R.raw.contactsdao),
        PathFile(listOf("cvforkhamidjon", "util", "ApiResponseHandler"), R.raw.apiresponsehandler),
        PathFile(listOf("cvforkhamidjon", "util", "glide", "GlideRequestManager"), R.raw.gliderequestmanager),
        PathFile(listOf("cvforkhamidjon", "util", "glide", "GlideManager"), R.raw.glidemanager),
        PathFile(listOf("cvforkhamidjon", "util", "WeightWrapper"), R.raw.weightwrapper),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "ProjectsViewHolder"), R.raw.projectsviewholder),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "ProjectsAdapter"), R.raw.projectsadapter),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "PostAdapter"), R.raw.postadapter),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "AchievementAdapter"), R.raw.achievementadapter),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "SkillsAdapter"), R.raw.skillsadapter),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "ContactMeViewHolderHim"), R.raw.contactmeviewholderhim),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "SkillViewHolder"), R.raw.skillviewholder),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "ContactMeViewHolderMe"), R.raw.contactmeviewholderme),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "AchievementViewHolder"), R.raw.achievementviewholder),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "PostViewHolder"), R.raw.postviewholder),
        PathFile(listOf("cvforkhamidjon", "util", "recycler", "ContactMeAdapter"), R.raw.contactmeadapter),
        PathFile(listOf("cvforkhamidjon", "util", "StateEvent"), R.raw.stateevent),
        PathFile(listOf("cvforkhamidjon", "util", "constants", "NetworkConstants"), R.raw.networkconstants),
        PathFile(listOf("cvforkhamidjon", "util", "constants", "GeneralConstants"), R.raw.generalconstants),
        PathFile(listOf("cvforkhamidjon", "util", "constants", "PERSONAL_INFO"), R.raw.personal_info),
        PathFile(listOf("cvforkhamidjon", "util", "constants", "ToFragment"), R.raw.tofragment),
        PathFile(listOf("cvforkhamidjon", "util", "constants", "DATABASE_CONSTANTS"), R.raw.database_constants),
        PathFile(listOf("cvforkhamidjon", "util", "NetworkConnection"), R.raw.networkconnection),
        PathFile(listOf("cvforkhamidjon", "util", "ApiResult"), R.raw.apiresult),
        PathFile(listOf("cvforkhamidjon", "util", "data_manager", "UIMessage"), R.raw.uimessage),
        PathFile(listOf("cvforkhamidjon", "util", "data_manager", "InboxManager"), R.raw.inboxmanager),
        PathFile(listOf("cvforkhamidjon", "util", "data_manager", "JobManager"), R.raw.jobmanager),
        PathFile(listOf("cvforkhamidjon", "util", "DataState"), R.raw.datastate),
        PathFile(listOf("cvforkhamidjon", "util", "DoublePostModel"), R.raw.doublepostmodel),
        PathFile(listOf("cvforkhamidjon", "util", "Message"), R.raw.message),
        PathFile(listOf("cvforkhamidjon", "util", "NavigationExtension"), R.raw.navigationextension),
        PathFile(listOf("cvforkhamidjon", "util", "shared_prefs", "RefreshLimitController"), R.raw.refreshlimitcontroller),
        PathFile(listOf("cvforkhamidjon", "util", "shared_prefs", "RefreshLimitControllerImpl"), R.raw.refreshlimitcontrollerimpl),
        PathFile(listOf("cvforkhamidjon", "util", "shared_prefs", "SharedPrefConstants"), R.raw.sharedprefconstants),
        PathFile(listOf("cvforkhamidjon", "util", "TokenStoreManager"), R.raw.tokenstoremanager),
        PathFile(listOf("cvforkhamidjon", "util", "DateUtil"), R.raw.dateutil),
        PathFile(listOf("cvforkhamidjon", "di", "contacts_subcomponent", "ContactsComponent"), R.raw.contactscomponent),
        PathFile(listOf("cvforkhamidjon", "di", "contacts_subcomponent", "ContactsScope"), R.raw.contactsscope),
        PathFile(listOf("cvforkhamidjon", "di", "contacts_subcomponent", "ContactsModuleAbstract"), R.raw.contactsmoduleabstract),
        PathFile(listOf("cvforkhamidjon", "di", "contacts_subcomponent", "ContactsFragmentModule"), R.raw.contactsfragmentmodule),
        PathFile(listOf("cvforkhamidjon", "di", "contacts_subcomponent", "ContactsModule"), R.raw.contactsmodule),
        PathFile(listOf("cvforkhamidjon", "di", "contacts_subcomponent", "ContactsViewModelFactoryModule"), R.raw.contactsviewmodelfactorymodule),
        PathFile(listOf("cvforkhamidjon", "di", "AppComponent"), R.raw.appcomponent),
        PathFile(listOf("cvforkhamidjon", "di", "main_subcomponent", "MainViewModelFactoryModule"), R.raw.mainviewmodelfactorymodule),
        PathFile(listOf("cvforkhamidjon", "di", "main_subcomponent", "MainModule"), R.raw.mainmodule),
        PathFile(listOf("cvforkhamidjon", "di", "main_subcomponent", "MainActivityScope"), R.raw.mainactivityscope),
        PathFile(listOf("cvforkhamidjon", "di", "main_subcomponent", "MainModuleAbstract"), R.raw.mainmoduleabstract),
        PathFile(listOf("cvforkhamidjon", "di", "main_subcomponent", "MainComponent"), R.raw.maincomponent),
        PathFile(listOf("cvforkhamidjon", "di", "main_subcomponent", "MainFragmentModule"), R.raw.mainfragmentmodule),
        PathFile(listOf("cvforkhamidjon", "di", "ViewModelKey"), R.raw.viewmodelkey),
        PathFile(listOf("cvforkhamidjon", "di", "AppModule"), R.raw.appmodule),
        PathFile(listOf("cvforkhamidjon", "di", "AppSubcomponents"), R.raw.appsubcomponents),
        PathFile(listOf("cvforkhamidjon", "di", "AppModuleAbstract"), R.raw.appmoduleabstract),
        PathFile(listOf("cvforkhamidjon", "di", "achievements_subcomponent", "AchievementsComponent"), R.raw.achievementscomponent),
        PathFile(listOf("cvforkhamidjon", "di", "achievements_subcomponent", "AchievmentsScope"), R.raw.achievmentsscope),
        PathFile(listOf("cvforkhamidjon", "di", "achievements_subcomponent", "AchievementsViewModelFactoryModule"), R.raw.achievementsviewmodelfactorymodule),
        PathFile(listOf("cvforkhamidjon", "di", "achievements_subcomponent", "AchievmentsFragmentModule"), R.raw.achievmentsfragmentmodule),
        PathFile(listOf("cvforkhamidjon", "di", "achievements_subcomponent", "AchievementModuleAbstract"), R.raw.achievementmoduleabstract),
        PathFile(listOf("cvforkhamidjon", "di", "achievements_subcomponent", "AchievementsModule"), R.raw.achievementsmodule),
        PathFile(listOf("cvforkhamidjon", "di", "InternalVariablesModule"), R.raw.internalvariablesmodule),
        PathFile(listOf("cvforkhamidjon", "ui", "c_source_code", "StaticData"), R.raw.staticdata),
        PathFile(listOf("cvforkhamidjon", "ui", "c_source_code", "FileHierarchyExtensions"), R.raw.filehierarchyextensions),
        PathFile(listOf("cvforkhamidjon", "ui", "c_source_code", "custom_tree_view", "Constants"), R.raw.constants),
        PathFile(listOf("cvforkhamidjon", "ui", "c_source_code", "custom_tree_view", "CreateViews"), R.raw.createviews),
        PathFile(listOf("cvforkhamidjon", "ui", "c_source_code", "custom_tree_view", "UtilFunctions"), R.raw.utilfunctions),
        PathFile(listOf("cvforkhamidjon", "ui", "c_source_code", "custom_tree_view", "FileView"), R.raw.fileview),
        PathFile(listOf("cvforkhamidjon", "ui", "c_source_code", "CodeViewActivity"), R.raw.codeviewactivity),
        PathFile(listOf("cvforkhamidjon", "ui", "c_source_code", "SourceCodeActivity"), R.raw.sourcecodeactivity),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "e_projects", "ProjectsFragment"), R.raw.projectsfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "viewmodel", "Setters"), R.raw.setters),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "viewmodel", "BaseMainViewModel"), R.raw.basemainviewmodel),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "viewmodel", "MainViewModel"), R.raw.mainviewmodel),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "viewmodel", "state", "MainViewState"), R.raw.mainviewstate),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "viewmodel", "state", "MainStateEvent"), R.raw.mainstateevent),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "viewmodel", "state", "MainViewDestEvent"), R.raw.mainviewdestevent),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "viewmodel", "state", "MainJobsEvent"), R.raw.mainjobsevent),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "viewmodel", "Getters"), R.raw.getters),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "c_myskills", "MySkillsFragment"), R.raw.myskillsfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "f_aboutapp", "AboutAppFragment"), R.raw.aboutappfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "MainActivity"), R.raw.mainactivity),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "f_posts", "PostsFragment"), R.raw.postsfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "a_home", "HomeFragment"), R.raw.homefragment),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "b_aboutme", "AboutMeFragment"), R.raw.aboutmefragment),
        PathFile(listOf("cvforkhamidjon", "ui", "a_main", "BaseMainFragment"), R.raw.basemainfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "viewmodel", "ContactViewModel"), R.raw.contactviewmodel),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "viewmodel", "Setters"), R.raw.setters),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "viewmodel", "state", "ContactsStateEvent"), R.raw.contactsstateevent),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "viewmodel", "state", "ContactsJobsEvent"), R.raw.contactsjobsevent),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "viewmodel", "state", "ContactsViewState"), R.raw.contactsviewstate),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "viewmodel", "state", "ContactsViewDestEvent"), R.raw.contactsviewdestevent),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "viewmodel", "Getters"), R.raw.getters),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "a_contact_me", "ContactMeFragment"), R.raw.contactmefragment),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "MessageNotifyModel"), R.raw.messagenotifymodel),
        PathFile(listOf("cvforkhamidjon", "ui", "d_contact", "ContactActivity"), R.raw.contactactivity),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "BaseAchievmentsFragment"), R.raw.baseachievmentsfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "viewmodel", "Getter"), R.raw.getter),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "viewmodel", "AchievementsViewModel"), R.raw.achievementsviewmodel),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "viewmodel", "state", "AchievementsViewDestEvent"), R.raw.achievementsviewdestevent),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "viewmodel", "state", "AchievementsStateEvent"), R.raw.achievementsstateevent),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "viewmodel", "state", "AchievementJobsEvent"), R.raw.achievementjobsevent),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "viewmodel", "state", "AchievementsViewState"), R.raw.achievementsviewstate),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "viewmodel", "BaseAchievmentsViewModel"), R.raw.baseachievmentsviewmodel),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "viewmodel", "Setter"), R.raw.setter),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "b_algorithms", "AlgorithmsFragment"), R.raw.algorithmsfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "BaseActivity"), R.raw.baseactivity),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "AchievmentsActivity"), R.raw.achievmentsactivity),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "d_detail", "DetailsFragment"), R.raw.detailsfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "a_android", "AndroidFragment"), R.raw.androidfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "b_achievments", "c_others", "OthersFragment"), R.raw.othersfragment),
        PathFile(listOf("cvforkhamidjon", "ui", "ActivityExtensions"), R.raw.activityextensions),
        PathFile(listOf("cvforkhamidjon", "fragment_builders", "main", "MainNavHostFragment"), R.raw.mainnavhostfragment),
        PathFile(listOf("cvforkhamidjon", "fragment_builders", "main", "MainFragmentFactory"), R.raw.mainfragmentfactory),
        PathFile(listOf("cvforkhamidjon", "fragment_builders", "contact", "ContactsFragmentFactory"), R.raw.contactsfragmentfactory),
        PathFile(listOf("cvforkhamidjon", "fragment_builders", "contact", "ContactsNavHostFragment"), R.raw.contactsnavhostfragment),
        PathFile(listOf("cvforkhamidjon", "fragment_builders", "achievment", "AchievmentsNavHostFragment"), R.raw.achievmentsnavhostfragment),
        PathFile(listOf("cvforkhamidjon", "fragment_builders", "achievment", "AchievementsFragmentFactory"), R.raw.achievementsfragmentfactory),
        PathFile(listOf("cvforkhamidjon", "models", "offline", "main", "AboutMeModel"), R.raw.aboutmemodel),
        PathFile(listOf("cvforkhamidjon", "models", "offline", "main", "ProjectModel"), R.raw.projectmodel),
        PathFile(listOf("cvforkhamidjon", "models", "offline", "main", "PostModel"), R.raw.postmodel),
        PathFile(listOf("cvforkhamidjon", "models", "offline", "main", "SkillModel"), R.raw.skillmodel),
        PathFile(listOf("cvforkhamidjon", "models", "offline", "achievements", "AchievementModel"), R.raw.achievementmodel),
        PathFile(listOf("cvforkhamidjon", "models", "offline", "contact", "MessageModel"), R.raw.messagemodel),
        PathFile(listOf("cvforkhamidjon", "models", "api", "achievments", "AchievementRemoteModel"), R.raw.achievementremotemodel),
        PathFile(listOf("cvforkhamidjon", "models", "api", "main", "ProjectRemoteModel"), R.raw.projectremotemodel),
        PathFile(listOf("cvforkhamidjon", "models", "api", "main", "SkillRemoteModel"), R.raw.skillremotemodel),
        PathFile(listOf("cvforkhamidjon", "models", "api", "main", "PostRemoteModel"), R.raw.postremotemodel),
        PathFile(listOf("cvforkhamidjon", "models", "api", "main", "AboutMeRemoteModel"), R.raw.aboutmeremotemodel),
        PathFile(listOf("cvforkhamidjon", "MyApplication"), R.raw.myapplication),
        PathFile(listOf("cvforkhamidjon", "services", "FMService"), R.raw.fmservice)
    )
}
























